#! /usr/bin/env bash

# Exit if a subprocess fails.
set -e

trap "rm -f .git/tags.tmp" EXIT
[ -e ./shard.yml ] && custom_exclude="--exclude=lib"
ctags-exuberant --tag-relative -Rf .git/tags.tmp --exclude=@$HOME/.ctagsignore $custom_exclude --languages=-sql
mv .git/tags.tmp .git/tags
