#! /usr/bin/env bash

# Exit if a subprocess fails.
set -e

trap "rm -f .git/tags.tmp" EXIT
ctags-exuberant --tag-relative -Rf .git/tags.tmp --exclude=.git --exclude=coverage --languages=-sql --exclude=*min.js
mv .git/tags.tmp .git/tags
