BS quit
] add chapter 1
[ add chapter -1
p show_text ${playlist}
a cycle audio
ctrl+[ quit 4
h seek -60
l seek 60
j seek -600
k seek 600
left seek -10
right seek 10
up add volume 1
down add volume -1
