submap = cursor

bind = , f, exec, hyprctl dispatch submap reset && wl-kbptr -o modes=floating,click -o mode_floating.source=detect && hyprctl dispatch submap cursor

# Cursor movement
binde = , j, exec, wlrctl pointer move 0 10
binde = , k, exec, wlrctl pointer move 0 -10
binde = , l, exec, wlrctl pointer move 10 0
binde = , h, exec, wlrctl pointer move -10 0

binde = SHIFT, j, exec, wlrctl pointer move 0 80
binde = SHIFT, k, exec, wlrctl pointer move 0 -80
binde = SHIFT, l, exec, wlrctl pointer move 80 0
binde = SHIFT, h, exec, wlrctl pointer move -80 0

bind = , o, exec, wlrctl pointer click left
bind = , m, exec, wlrctl pointer click middle
bind = , r, exec, wlrctl pointer click right

# Scroll up and down
binde = , t, exec, wlrctl pointer scroll 30 0
binde = , g, exec, wlrctl pointer scroll -30 0

# Scroll left and right
binde = , a, exec, wlrctl pointer scroll 0 -30
binde = , s, exec, wlrctl pointer scroll 0 30

bind = , escape, exec, hyprctl keyword cursor:inactive_timeout 3; hyprctl keyword cursor:hide_on_key_press true; hyprctl dispatch submap reset

submap  =  reset

bind = SUPER SHIFT, F, exec, hyprctl keyword cursor:inactive_timeout 0; hyprctl keyword cursor:hide_on_key_press false; hyprctl dispatch submap cursor

unbind = SUPER, F
bind = SUPER, F, exec, wl-kbptr -o modes=floating,click -o mode_floating.source=detect
