#! /usr/bin/ruby
if ARGV[1]
  command = "git push #{ARGV[0]} #{ARGV[1]}"
else
  branch_string = %x[ git branch ]
  branch_name = branch_string.slice(/\* (\w+)/, 1)
  branch = ARGV[0] || branch_name
  command = case branch
    when 'd'
      "git push origin develop"
    when 'r'
      "git push origin release"
    when 'm'
      "git push origin master"
    else
      "git push origin #{branch}"
    end
end
puts command
system command
