#! /usr/bin/ruby
if ARGV[1]
  command = "git push #{ARGV[0]} #{ARGV[1]}"
else
  branch_string = %x[ git branch ]
  branch_name = branch_string.slice(/\* (\w+)/, 1)
  branch = ARGV[0] || branch_name
  remote_name = case branch
                when 'd'
                  "develop"
                when 'r'
                  "release"
                when 'm'
                  "master"
                when 't'
                  "temp"
                else
                  branch
                end
  command = "git push origin #{branch_name}:#{remote_name}"
end
puts command
system command
