#! /usr/bin/ruby
case ARGV[0]
when 'd'
  command = "screen -c ~/.screen/screem"
when 't'
  command = "screen -c ~/.screen/screemtest"
when 'm'
  command = "screen -c ~/.screen/screemini"
end
system command rescue puts "acceptable parameters: d m t"
