#! /usr/bin/ruby

require 'optparse'

options = ARGV.getopts('m', 'f')

params = ''
params += '-f' if options['f']
params += '; heroku run rake db:migrate --app=ikonverse-staging' if options['m']

branch_string = %x[ git branch ]
branch_name = branch_string.slice(/\* (\w+)/, 1)

command = "git push staging #{ branch_name }:master #{ params }"
puts command
system command
