#! /bin/bash

new_window() {
  [ $2 ] && local new_window_opts="-n $2"
  tmux new-window -t $session_name:$1 ${new_window_opts}
}

run_command() {
  tmux send-keys -t $session_name:$1 "$2" C-m
}

create_session() {
  tmux start-server
  tmux -u2 new-session -d -s $session_name # -d starts in detached mode
}

run_git_pull_at() {
  run_command $1 'git pull origin master'
}

setup_gitbasket_at() {
  run_command $1 'cd ~/gitbasket'

  [ $pull_from_repo ] && run_git_pull_at $1

  run_command $1 'vim WorkFlow.notes'
}

common_setup() {
  new_window 3 vim
  new_window 4 notes

  run_command 3 vim
  setup_gitbasket_at 4
}

rails_setup() {
  new_window 2 vim
  new_window 9 console
  new_window 7
  new_window 8

  run_command 0 'rails server'
  run_command 2 'vim'
  run_command 9 'rails console'
}

setup_spork_at() {
  new_window $1 spork
  run_command $1 'rake db:migrate RAILS_ENV=test; git checkout db/schema.rb; spork cucumber'
}

experiments_setup() {
  new_window 2 vim
  new_window 9 console

  run_command 2 "cd $HOME/experiments/$experiments_folder; vim"
  run_command 7 "pushd $HOME/experiments/$experiments_folder"
  run_command 9 'irb'
}

minimal_setup() {
  new_window 7
}

attach_session() {
  tmux select-window -t $session_name:3
  tmux -u2 attach-session -t $session_name
}

echo_help() {
  echo '-g do a git pull'
  echo '-e <experiments folder name>'
  echo '-n <session name>'
}

assign_name() {
  [ -z $session_name ] && session_name=$session_type
}

small_setup() {
  minimal_setup
}

exp_setup() {
  minimal_setup
  experiments_setup
}

medium_setup() {
  rails_setup
}

large_setup() {
  rails_setup
  new_window 6
  setup_spork_at 11
}

setup_tmux() {
  assign_name
  create_session
  common_setup
  ${session_type}_setup
  [ $pull_from_repo ] && run_git_pull_at 7
  attach_session
}

session_type=small
while getopts e:hn:gml flag; do
  case $flag in
    g) pull_from_repo=0 ;;
    n) session_name=$OPTARG ;;

    e) experiments_folder=$OPTARG
       session_type=exp ;;
    l) session_type=large ;;
    m) session_type=medium ;;

    h) echo_help; exit ;;
    *) exit ;;
  esac
done

setup_tmux
