#! /bin/bash

common_setup() {
  tmux start-server
  tmux -u2 new-session -d -s $session_name -n vi    # start in detached mode and attach later # -s specifies name of new-session
  tmux new-window -t $session_name:8 -n notes

  tmux send-keys -t $session_name:8 "cd ~/gitbasket; git pull origin master; vim -p2 ~/gitbasket/WorkFlow.notes ~/gitbasket/ruby.notes" C-m
  tmux send-keys -t $session_name:1 "vim" C-m
}

rails_setup() {
  tmux new-window -t $session_name:0 -n server              # -t refers to target which could be session/window/pane/client
  tmux new-window -t $session_name:2 -n vi
  tmux new-window -t $session_name:3
  tmux new-window -t $session_name:4
  tmux new-window -t $session_name:9 -n console

  tmux send-keys -t $session_name:0 "rails server" C-m
  tmux send-keys -t $session_name:2 "vim" C-m
  tmux send-keys -t $session_name:9 "rails console" C-m
}

develop_setup() {
  tmux new-window -t $session_name:5
  tmux new-window -t $session_name:11 -n spork

  tmux send-keys -t $session_name:11 "spork cucumber" C-m
}

minimal_setup() {
  tmux new-window -t $session_name:0

  tmux send-keys -t $session_name:0 "git pull origin master" C-m
}

session_attach() {
  tmux select-window -t $session_name:8
  tmux -u2 attach-session -t $session_name       # flags like -u need to be specified while creation and attach
}

assign_name() {
  if [ -n "$2" ]; then
    session_name=$2
  else
    session_name=$1
  fi
}

case $1 in
  l)
    assign_name Large $2
    common_setup
    rails_setup
    develop_setup
    session_attach
    ;;
  m)
    assign_name Medium $2
    common_setup
    rails_setup
    session_attach
    ;;
  s)
    assign_name Small $2
    common_setup
    minimal_setup
    session_attach
    ;;
  *)
    echo "Acceptable parameters: l m s"
    ;;
esac
