#! /usr/bin/env bash

read -r -p "Are you sure? [y/n] " response

if [ "$1" != "" ]; then
  head=$1
else
  head=1
fi

case $response in
  y)
    eval "git reset --soft HEAD~$head"
  ;;
  *)
    echo "no reset done"
  ;;
esac
