#! /usr/bin/env bash
source $HOME/.git_helpers/remote_and_branch.sh

cmd="git push $(remote_name) $(branch_name):$(remote_branch_name $@) $(force_option $@)"

echo $cmd
eval $cmd && write_pushed_head
